
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftANDORleftIFIFFnonassocNEGNEG AND OR IF IFF LPAREN RPAREN VARIABLE CONSTANTexpr : CONSTANTexpr : VARIABLEexpr : NEG exprexpr : expr AND exprexpr : expr OR exprexpr : expr IF exprexpr : expr IFF exprexpr : LPAREN expr RPAREN'
    
_lr_action_items = {'CONSTANT':([0,4,5,6,7,8,9,],[2,2,2,2,2,2,2,]),'VARIABLE':([0,4,5,6,7,8,9,],[3,3,3,3,3,3,3,]),'NEG':([0,4,5,6,7,8,9,],[4,4,4,4,4,4,4,]),'LPAREN':([0,4,5,6,7,8,9,],[5,5,5,5,5,5,5,]),'$end':([1,2,3,10,12,13,14,15,16,],[0,-1,-2,-3,-4,-5,-6,-7,-8,]),'AND':([1,2,3,10,11,12,13,14,15,16,],[6,-1,-2,-3,6,-4,-5,-6,-7,-8,]),'OR':([1,2,3,10,11,12,13,14,15,16,],[7,-1,-2,-3,7,-4,-5,-6,-7,-8,]),'IF':([1,2,3,10,11,12,13,14,15,16,],[8,-1,-2,-3,8,8,8,-6,-7,-8,]),'IFF':([1,2,3,10,11,12,13,14,15,16,],[9,-1,-2,-3,9,9,9,-6,-7,-8,]),'RPAREN':([2,3,10,11,12,13,14,15,16,],[-1,-2,-3,16,-4,-5,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,5,6,7,8,9,],[1,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> CONSTANT','expr',1,'p_constant2expr','Language.py',76),
  ('expr -> VARIABLE','expr',1,'p_variable2expr','Language.py',81),
  ('expr -> NEG expr','expr',2,'p_neg','Language.py',86),
  ('expr -> expr AND expr','expr',3,'p_and','Language.py',93),
  ('expr -> expr OR expr','expr',3,'p_or','Language.py',101),
  ('expr -> expr IF expr','expr',3,'p_if','Language.py',109),
  ('expr -> expr IFF expr','expr',3,'p_iff','Language.py',117),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_parens','Language.py',125),
]
